#!/usr/bin/env bash
#specific iterations on line 9/10

count=1
while [ $count -le 10 ];
do
    echo "Best School"

    if [ $count -eq 9 ];
    then
        echo "Hi"
    fi
        (( count++ ))
done
