#!/usr/bin/env bash
#if - elif and more

count=1
while [ $count -le 5 ];
do
    echo "Best School"
    if [ $count -eq 2 ];then
	echo "bad luck"

    elif [ $count -eq 4 ];then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( count++ ))
done
