#!/usr/bin/env bash
#if - elif and more

count=1

while [ $count -le 8 ];
do
    echo "Best School"
    if [[ $count -eq 3 ]];then
       echo "bad luck"
       elif [[ $count -eq 6 ]]; then
    	 echo "good luck"
	 fi
    (( count++ ))
done
