#!/usr/bin/env bash
#while cycle

count=1
number=0

while [ "$number" -le "12" ];
do
    echo "Hour:$number"
    (( number++ ))
    while [ "$count" -le "59" ];
    do 
    echo "$count"
    (( count++ ))
    done
    count=1
done
